services:
  endpoint.api:
    image: endpoint.api
    build:
      context: .
      dockerfile: src/Endpoint.Api/Dockerfile

  endpoint.api-1:
    image: endpoint.api-1
    build:
      context: .
      dockerfile: src/Endpoint.Api/Dockerfile
